//
//  Symbols.swift
//  Tibby
//
//  Created by Natalia Dal Pizzol on 17/07/24.
//

import Foundation

enum TibbySymbols: String {
    case arrowDownWhite = "TibbySymbolArrowDownLight"
    case arrowDownBlack = "TibbySymbolArrowDownDark"
    case arrowUpWhite = "TibbySymbolArrowUpLight"
    case arrowUpBlack = "TibbySymbolArrowUpDark"
    case arrowUpDiagonalWhite = "TibbySymbolArrowUpDiagonalLight"
    case arrowUpDiagonalGrey = "TibbySymbolArrowUpDiagonalGrey"
    case arrowUpDiagonalBlack = "TibbySymbolArrowUpDiagonalDark"
    case atWhite = "TibbySymbolAtLight"
    case atBlack = "TibbySymbolAtDark"
    case ballWhite = "TibbySymbolBallLight"
    case ballBlack = "TibbySymbolBallDark"
    case bookWhite = "TibbySymbolBookLight"
    case bookBlack = "TibbySymbolBookDark"
    case carrotWhite = "TibbySymbolCarrotLight"
    case carrotBlack = "TibbySymbolCarrotDark"
    case cartWhite = "TibbySymbolCartLight"
    case cartBlack = "TibbySymbolCartDark"
    case checkmarkWhite = "TibbySymbolCheckmarkLight"
    case checkmarkBlack = "TibbySymbolCheckmarkDark"
    case chevronLeftWhite = "TibbySymbolChevronLeftLight"
    case chevronLeftBlack = "TibbySymbolChevronLeftDark"
    case chevronRightWhite = "TibbySymbolChevronRightLight"
    case chevronRightBlack = "TibbySymbolChevronRightDark"
    case chevronRightGrey = "TibbySymbolChevronRightGreyDark"
    case controllerWhite = "TibbySymbolControllerLight"
    case controllerBlack = "TibbySymbolControllerDark"
    case dumbbellWhite = "TibbySymbolDumbbellLight"
    case dumbbellBlack = "TibbySymbolDumbbellDark"
    case duplicateWhite = "TibbySymbolDuplicateLight"
    case duplicateBlack = "TibbySymbolDuplicateDark"
    case emptyWhite = "TibbySymbolEmptyLight"
    case emptyBlack = "TibbySymbolEmptyDark"
    case envelopeWhite = "TibbySymbolEnvelopeLight"
    case envelopeBlack = "TibbySymbolEnvelopeDark"
    case gearWhite = "TibbySymbolGearLight"
    case gearBlack = "TibbySymbolGearDark"
    case hangerWhite = "TibbySymbolHangerLight"
    case hangerBlack = "TibbySymbolHangerDark"
    case heartWhite = "TibbySymbolHeartLight"
    case heartBlack = "TibbySymbolHeartDark"
    case heartFillWhite = "TibbySymbolHeartFillLight"
    case heartFillBlack = "TibbySymbolHeartFillDark"
    case homeWhite = "TibbySymbolHomeLight"
    case homeBlack = "TibbySymbolHomeDark"
    case kitchenWhite = "TibbySymbolKitchenLight"
    case kitchenBlack = "TibbySymbolKitchenDark"
    case lightbulbWhite = "TibbySymbolLightbulbLight"
    case lightbulbBlack = "TibbySymbolLightbulbDark"
    case listWhite = "TibbySymbolListLight"
    case listBlack = "TibbySymbolListDark"
    case lockWhite = "TibbySymbolLockLight"
    case lockBlack = "TibbySymbolLockDark"
    case minusWhite = "TibbySymbolMinusLight"
    case minusBlack = "TibbySymbolMinusDark"
    case pauseWhite = "TibbySymbolPauseLight"
    case pauseBlack = "TibbySymbolPauseDark"
    case penWhite = "TibbySymbolPenLight"
    case penBlack = "TibbySymbolPenDark"
    case playWhite = "TibbySymbolPlayLight"
    case playBlack = "TibbySymbolPlayDark"
    case plusWhite = "TibbySymbolPlusLight"
    case plusBlack = "TibbySymbolPlusDark"
    case profileWhite = "TibbySymbolProfileLight"
    case profileBlack = "TibbySymbolProfileDark"
    case questionWhite = "TibbySymbolQuestionLight"
    case questionBlack = "TibbySymbolQuestionDark"
    case rollWhite = "TibbySymbolRollLight"
    case rollBlack = "TibbySymbolRollDark"
    case searchWhite = "TibbySymbolSearchLight"
    case searchBlack = "TibbySymbolSearchDark"
    case sleepWhite = "TibbySymbolSleepLight"
    case sleepBlack = "TibbySymbolSleepDark"
    case squareWhite = "TibbySymbolSquareLight"
    case squareBlack = "TibbySymbolSquareWhiteDark"
    case starWhite = "TibbySymbolStarLight"
    case starBlack = "TibbySymbolStarDark"
    case starListWhite = "TibbySymbolStarListLight"
    case starListBlack = "TibbySymbolStarListDark"
    case stepsWhite = "TibbySymbolStepsLight"
    case stepsBlack = "TibbySymbolStepsDark"
    case xmarkWhite = "TibbySymbolXMarkLight"
    case xmarkBlack = "TibbySymbolXMarkDark"
    case adLight = "TibbySymbolAdLight"
}
